#!/bin/sh

build/RTDecodeTest
build/RTEncodeTest
build/RTExecuteTest
build/RTIdentifierTest
build/RTListTest
build/RTMemoryTest
build/RTMapTest
build/RTOperationTest
build/RTStringTest
build/RTValueTest
